//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KHakhakhakha
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "Наим as \'ФИО\'",
            "НомерТел as \'Номер телефона\'",
            "ДР as \'Дата рождения\'",
            "БанкДан as \'Номер карты\'",
            "БанкДан.НомКарт as \'Номер карты\'"})]
    [AssociatedDetailViewAttribute("КлиентE", "ТЧКл", "ТЧКлE", true, "", "Табличная часть Клиент", true, new string[] {
            ""})]
    [View("КлиентL", new string[] {
            "Наим as \'ФИО\'",
            "НомерТел as \'Номер телефона\'",
            "ДР as \'Дата рождения\'",
            "БанкДан.НомКарт as \'Номер карты\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомерТел;
        
        private string fНаим;
        
        private System.DateTime fДР;
        
        private IIS.KHakhakhakha.БанкДан fБанкДан;
        
        private IIS.KHakhakhakha.DetailArrayOfТЧКл fТЧКл;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// ДР.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ДР CustomAttributes)

        // *** End programmer edit section *** (Клиент.ДР CustomAttributes)
        public virtual System.DateTime ДР
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ДР Get start)

                // *** End programmer edit section *** (Клиент.ДР Get start)
                System.DateTime result = this.fДР;
                // *** Start programmer edit section *** (Клиент.ДР Get end)

                // *** End programmer edit section *** (Клиент.ДР Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ДР Set start)

                // *** End programmer edit section *** (Клиент.ДР Set start)
                this.fДР = value;
                // *** Start programmer edit section *** (Клиент.ДР Set end)

                // *** End programmer edit section *** (Клиент.ДР Set end)
            }
        }
        
        /// <summary>
        /// Наим.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Наим CustomAttributes)

        // *** End programmer edit section *** (Клиент.Наим CustomAttributes)
        [StrLen(255)]
        public virtual string Наим
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Наим Get start)

                // *** End programmer edit section *** (Клиент.Наим Get start)
                string result = this.fНаим;
                // *** Start programmer edit section *** (Клиент.Наим Get end)

                // *** End programmer edit section *** (Клиент.Наим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Наим Set start)

                // *** End programmer edit section *** (Клиент.Наим Set start)
                this.fНаим = value;
                // *** Start programmer edit section *** (Клиент.Наим Set end)

                // *** End programmer edit section *** (Клиент.Наим Set end)
            }
        }
        
        /// <summary>
        /// НомерТел.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.НомерТел CustomAttributes)

        // *** End programmer edit section *** (Клиент.НомерТел CustomAttributes)
        [StrLen(255)]
        public virtual string НомерТел
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.НомерТел Get start)

                // *** End programmer edit section *** (Клиент.НомерТел Get start)
                string result = this.fНомерТел;
                // *** Start programmer edit section *** (Клиент.НомерТел Get end)

                // *** End programmer edit section *** (Клиент.НомерТел Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.НомерТел Set start)

                // *** End programmer edit section *** (Клиент.НомерТел Set start)
                this.fНомерТел = value;
                // *** Start programmer edit section *** (Клиент.НомерТел Set end)

                // *** End programmer edit section *** (Клиент.НомерТел Set end)
            }
        }
        
        /// <summary>
        /// Клиент.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.БанкДан CustomAttributes)

        // *** End programmer edit section *** (Клиент.БанкДан CustomAttributes)
        [PropertyStorage(new string[] {
                "БанкДан"})]
        [NotNull()]
        public virtual IIS.KHakhakhakha.БанкДан БанкДан
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.БанкДан Get start)

                // *** End programmer edit section *** (Клиент.БанкДан Get start)
                IIS.KHakhakhakha.БанкДан result = this.fБанкДан;
                // *** Start programmer edit section *** (Клиент.БанкДан Get end)

                // *** End programmer edit section *** (Клиент.БанкДан Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.БанкДан Set start)

                // *** End programmer edit section *** (Клиент.БанкДан Set start)
                this.fБанкДан = value;
                // *** Start programmer edit section *** (Клиент.БанкДан Set end)

                // *** End programmer edit section *** (Клиент.БанкДан Set end)
            }
        }
        
        /// <summary>
        /// Клиент.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ТЧКл CustomAttributes)

        // *** End programmer edit section *** (Клиент.ТЧКл CustomAttributes)
        public virtual IIS.KHakhakhakha.DetailArrayOfТЧКл ТЧКл
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ТЧКл Get start)

                // *** End programmer edit section *** (Клиент.ТЧКл Get start)
                if ((this.fТЧКл == null))
                {
                    this.fТЧКл = new IIS.KHakhakhakha.DetailArrayOfТЧКл(this);
                }
                IIS.KHakhakhakha.DetailArrayOfТЧКл result = this.fТЧКл;
                // *** Start programmer edit section *** (Клиент.ТЧКл Get end)

                // *** End programmer edit section *** (Клиент.ТЧКл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ТЧКл Set start)

                // *** End programmer edit section *** (Клиент.ТЧКл Set start)
                this.fТЧКл = value;
                // *** Start programmer edit section *** (Клиент.ТЧКл Set end)

                // *** End programmer edit section *** (Клиент.ТЧКл Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.KHakhakhakha.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.KHakhakhakha.Клиент));
                }
            }
        }
    }
}
