//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KHakhakhakha
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТЧКл.
    /// </summary>
    // *** Start programmer edit section *** (ТЧКл CustomAttributes)

    // *** End programmer edit section *** (ТЧКл CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧКлE", new string[] {
            "Продукт as \'Продукт\'",
            "колво as \'Количество продуктов\'"})]
    public class ТЧКл : ICSSoft.STORMNET.DataObject
    {
        
        private string fПродукт;
        
        private int fколво;
        
        private IIS.KHakhakhakha.Клиент fКлиент;
        
        // *** Start programmer edit section *** (ТЧКл CustomMembers)

        // *** End programmer edit section *** (ТЧКл CustomMembers)

        
        /// <summary>
        /// колво.
        /// </summary>
        // *** Start programmer edit section *** (ТЧКл.колво CustomAttributes)

        // *** End programmer edit section *** (ТЧКл.колво CustomAttributes)
        public virtual int колво
        {
            get
            {
                // *** Start programmer edit section *** (ТЧКл.колво Get start)

                // *** End programmer edit section *** (ТЧКл.колво Get start)
                int result = this.fколво;
                // *** Start programmer edit section *** (ТЧКл.колво Get end)

                // *** End programmer edit section *** (ТЧКл.колво Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧКл.колво Set start)

                // *** End programmer edit section *** (ТЧКл.колво Set start)
                this.fколво = value;
                // *** Start programmer edit section *** (ТЧКл.колво Set end)

                // *** End programmer edit section *** (ТЧКл.колво Set end)
            }
        }
        
        /// <summary>
        /// Продукт.
        /// </summary>
        // *** Start programmer edit section *** (ТЧКл.Продукт CustomAttributes)

        // *** End programmer edit section *** (ТЧКл.Продукт CustomAttributes)
        [StrLen(255)]
        public virtual string Продукт
        {
            get
            {
                // *** Start programmer edit section *** (ТЧКл.Продукт Get start)

                // *** End programmer edit section *** (ТЧКл.Продукт Get start)
                string result = this.fПродукт;
                // *** Start programmer edit section *** (ТЧКл.Продукт Get end)

                // *** End programmer edit section *** (ТЧКл.Продукт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧКл.Продукт Set start)

                // *** End programmer edit section *** (ТЧКл.Продукт Set start)
                this.fПродукт = value;
                // *** Start programmer edit section *** (ТЧКл.Продукт Set end)

                // *** End programmer edit section *** (ТЧКл.Продукт Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.KHakhakhakha.Клиент.
        /// </summary>
        // *** Start programmer edit section *** (ТЧКл.Клиент CustomAttributes)

        // *** End programmer edit section *** (ТЧКл.Клиент CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Клиент"})]
        public virtual IIS.KHakhakhakha.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (ТЧКл.Клиент Get start)

                // *** End programmer edit section *** (ТЧКл.Клиент Get start)
                IIS.KHakhakhakha.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (ТЧКл.Клиент Get end)

                // *** End programmer edit section *** (ТЧКл.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧКл.Клиент Set start)

                // *** End programmer edit section *** (ТЧКл.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (ТЧКл.Клиент Set end)

                // *** End programmer edit section *** (ТЧКл.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧКлE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧКлE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧКлE", typeof(IIS.KHakhakhakha.ТЧКл));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧКл.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧКл CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧКл CustomAttributes)
    public class DetailArrayOfТЧКл : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.KHakhakhakha.DetailArrayOfТЧКл members)

        // *** End programmer edit section *** (IIS.KHakhakhakha.DetailArrayOfТЧКл members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧКл by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧКл.
        /// </summary>
        public DetailArrayOfТЧКл(IIS.KHakhakhakha.Клиент fКлиент) : 
                base(typeof(ТЧКл), ((ICSSoft.STORMNET.DataObject)(fКлиент)))
        {
        }
        
        public IIS.KHakhakhakha.ТЧКл this[int index]
        {
            get
            {
                return ((IIS.KHakhakhakha.ТЧКл)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.KHakhakhakha.ТЧКл dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
